/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type AccessPathCreateReqAccessPath struct {

	Chap bool `json:"chap,omitempty"`

	Description string `json:"description,omitempty"`

	HostIds []int64 `json:"host_ids,omitempty"`

	MappingGroups []MappingGroupReq `json:"mapping_groups,omitempty"`

	Name string `json:"name,omitempty"`

	ProtectionDomainId int64 `json:"protection_domain_id,omitempty"`

	Tname string `json:"tname,omitempty"`

	Tsecret string `json:"tsecret,omitempty"`

	Type_ string `json:"type,omitempty"`
}
