/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type AlertStats struct {

	CriticalNum int64 `json:"critical_num,omitempty"`

	ErrorNum int64 `json:"error_num,omitempty"`

	InfoNum int64 `json:"info_num,omitempty"`

	WarningNum int64 `json:"warning_num,omitempty"`
}
