/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type AlertRuleCreateReqRule struct {

	Enabled bool `json:"enabled,omitempty"`

	Level string `json:"level,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`

	TriggerMode string `json:"trigger_mode,omitempty"`

	TriggerPeriod int64 `json:"trigger_period,omitempty"`

	TriggerValue string `json:"trigger_value,omitempty"`

	Type_ string `json:"type,omitempty"`
}
