/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type BootNodeReqBootNode struct {

	// admin network: 10.0.0.0/24
	AdminNetwork string `json:"admin_network,omitempty"`

	// gateway networks, multiple networks splited by comma: 10.0.3.0/24,10.0.4.0/24
	GatewayNetwork string `json:"gateway_network,omitempty"`

	// private network : 10.0.2.0/24
	PrivateNetwork string `json:"private_network"`

	// public network: 10.0.1.0/24
	PublicNetwork string `json:"public_network"`
}
