/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type BucketFlagReq struct {

	// set versioned flag
	Versioned bool `json:"versioned,omitempty"`

	// set versioned suspended flag
	VersionsSuspended bool `json:"versions_suspended,omitempty"`

	// set worm flag
	Worm bool `json:"worm,omitempty"`
}
