/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ChunkRecord defines chunks api response
type ChunkRecord struct {

	ChunkId string `json:"chunk_id,omitempty"`

	Id int64 `json:"id,omitempty"`

	OsdIds []int64 `json:"osd_ids,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Scrubs []PlacementGroupScrub `json:"scrubs,omitempty"`
}
