/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// CloudPlatform defines different cloud platforms
type CloudPlatform struct {

	ActionStatus string `json:"action_status,omitempty"`

	AttachedCloudVolumeNum int64 `json:"attached_cloud_volume_num,omitempty"`

	CloudInstanceNum int64 `json:"cloud_instance_num,omitempty"`

	CloudVolumeNum int64 `json:"cloud_volume_num,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Description string `json:"description,omitempty"`

	ExtraProperties *CloudExtraProperties `json:"extra_properties,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`

	SyncTime time.Time `json:"sync_time,omitempty"`

	Type_ string `json:"type,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Url string `json:"url,omitempty"`

	Username string `json:"username,omitempty"`
}
