/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// CloudInstanceStat represents the monitoring metrics of a cloud instance
type CloudInstanceStat struct {

	Create time.Time `json:"create,omitempty"`

	ReadBandwidthKbyte float64 `json:"read_bandwidth_kbyte,omitempty"`

	ReadIops float64 `json:"read_iops,omitempty"`

	ReadLatencyUs float64 `json:"read_latency_us,omitempty"`

	TotalBandwidthKbyte float64 `json:"total_bandwidth_kbyte,omitempty"`

	TotalIops float64 `json:"total_iops,omitempty"`

	WriteBandwidthKbyte float64 `json:"write_bandwidth_kbyte,omitempty"`

	WriteIops float64 `json:"write_iops,omitempty"`

	WriteLatencyUs float64 `json:"write_latency_us,omitempty"`
}
