/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// DpBlockBackupPolicy protects a block volume by backup snapshot to remote site
type DpBlockBackupPolicy struct {

	BlockVolumeNum int64 `json:"block_volume_num,omitempty"`

	Create time.Time `json:"create,omitempty"`

	DpGateway *DpGatewayNestview `json:"dp_gateway,omitempty"`

	DpSite *DpSiteNestview `json:"dp_site,omitempty"`

	Encrypted bool `json:"encrypted,omitempty"`

	FullCronExpr string `json:"full_cron_expr,omitempty"`

	Id int64 `json:"id,omitempty"`

	IncCronExpr string `json:"inc_cron_expr,omitempty"`

	Name string `json:"name,omitempty"`

	RetainedMax int64 `json:"retained_max,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
