/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type DpBlockReplicationPolicyCreateReqPolicy struct {

	// protection site id
	DpSiteId int64 `json:"dp_site_id"`

	// name
	Name string `json:"name"`

	// replication timeout seconds
	TimeoutSeconds int64 `json:"timeout_seconds"`
}
