/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// DpBlockSnapshotRecoveryJob recovery a block resource
type DpBlockSnapshotRecoveryJob struct {

	BackupBlockSnapshot *DpBackupBlockSnapshot `json:"backup_block_snapshot,omitempty"`

	BackupBlockVolume *DpBackupBlockVolume `json:"backup_block_volume,omitempty"`

	BackupCluster *DpBackupCluster `json:"backup_cluster,omitempty"`

	BlockVolume *VolumeNestview `json:"block_volume,omitempty"`

	Create time.Time `json:"create,omitempty"`

	DpGateway *DpGatewayNestview `json:"dp_gateway,omitempty"`

	DpSite *DpSiteNestview `json:"dp_site,omitempty"`

	FinishedAt time.Time `json:"finished_at,omitempty"`

	Id int64 `json:"id,omitempty"`

	MaxRetryTimes int64 `json:"max_retry_times,omitempty"`

	Progress float64 `json:"progress,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`

	StartedAt time.Time `json:"started_at,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
