/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// DpFSSnapshotPolicy protects a fs folder by snapshot
type DpFsSnapshotPolicy struct {

	Create time.Time `json:"create,omitempty"`

	CronExpr string `json:"cron_expr,omitempty"`

	DpGateway *DpGatewayNestview `json:"dp_gateway,omitempty"`

	FsFolderNum int64 `json:"fs_folder_num,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	RetainedMax int64 `json:"retained_max,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
