/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type DpFsSnapshotPolicyUpdateReqPolicy struct {

	CronExpr string `json:"cron_expr,omitempty"`

	Name string `json:"name,omitempty"`

	RetainedMax int64 `json:"retained_max,omitempty"`
}
