/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// DpSite is a site to storage data protection data
type DpSite struct {

	Address string `json:"address,omitempty"`

	Config *DpSiteConfig `json:"config,omitempty"`

	Create time.Time `json:"create,omitempty"`

	CryptoKey *CryptoKeyNestview `json:"crypto_key,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Platform string `json:"platform,omitempty"`

	ProtectionType string `json:"protection_type,omitempty"`

	RemoteCluster *RemoteClusterNestview `json:"remote_cluster,omitempty"`

	Service string `json:"service,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
