/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// EmailGroup defines the email group
type EmailGroup struct {

	Create time.Time `json:"create,omitempty"`

	Emails []string `json:"emails,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
