/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// EventLog defines a system event
type EventLog struct {

	// create time
	Create time.Time `json:"create,omitempty"`

	// dumped resource data
	Data *interface{} `json:"data,omitempty"`

	// evnet type
	Event string `json:"event,omitempty"`

	// host eventlog generated on
	Host *HostNestview `json:"host,omitempty"`

	Id int64 `json:"id,omitempty"`

	// debug message
	Message string `json:"message,omitempty"`

	// resource id
	ResourceId int64 `json:"resource_id,omitempty"`

	// resource type
	ResourceType string `json:"resource_type,omitempty"`

	// eventlog created by
	User *UserNestview `json:"user,omitempty"`
}
