/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// FSActiveDirectory defines file storage active directory
type FsActiveDirectory struct {

	ActionStatus string `json:"action_status,omitempty"`

	Create time.Time `json:"create,omitempty"`

	FsGatewayGroupNum int64 `json:"fs_gateway_group_num,omitempty"`

	Id int64 `json:"id,omitempty"`

	Ip string `json:"ip,omitempty"`

	Name string `json:"name,omitempty"`

	Realm string `json:"realm,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Username string `json:"username,omitempty"`

	VerifyTime time.Time `json:"verify_time,omitempty"`

	Workgroup string `json:"workgroup,omitempty"`
}
