/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// FSGateway defines model of file storage gateway @grpc-models-proto
type FsGateway struct {

	Create time.Time `json:"create,omitempty"`

	FsGatewayGroup *FsGatewayGroupNestview `json:"fs_gateway_group,omitempty"`

	Host *HostNestview `json:"host,omitempty"`

	Id int64 `json:"id,omitempty"`

	NetworkAddress *NetworkAddressNestview `json:"network_address,omitempty"`

	NicName string `json:"nic_name,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Vip string `json:"vip,omitempty"`
}
