/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// FSSMBShare defines model of fs smb share
type FssmbShare struct {

	AclInherited bool `json:"acl_inherited,omitempty"`

	AclNum int64 `json:"acl_num,omitempty"`

	ActionStatus string `json:"action_status,omitempty"`

	CaseSensitive bool `json:"case_sensitive,omitempty"`

	Create time.Time `json:"create,omitempty"`

	FsFolder *FsFolderNestview `json:"fs_folder,omitempty"`

	FsGatewayGroup *FsGatewayGroupNestview `json:"fs_gateway_group,omitempty"`

	FsQuotaTree *FsQuotaTreeNestview `json:"fs_quota_tree,omitempty"`

	Id int64 `json:"id,omitempty"`

	MappingNum int64 `json:"mapping_num,omitempty"`

	Name string `json:"name,omitempty"`

	Recycled bool `json:"recycled,omitempty"`

	Security string `json:"security,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
