/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// HostEncSpec defines host enclosure specification
type HostEncSpec struct {

	Create time.Time `json:"create,omitempty"`

	Enclosures []Enclosure `json:"enclosures,omitempty"`

	Id int64 `json:"id,omitempty"`

	Model string `json:"model,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Vendor string `json:"vendor,omitempty"`
}
