/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// IdentityPlatform defines different platforms for auth
type IdentityPlatform struct {

	// time of creating identity platform
	Create time.Time `json:"create,omitempty"`

	// enable the identity platform or not
	Enabled bool `json:"enabled,omitempty"`

	// num of failed authorization
	FailureNum int64 `json:"failure_num,omitempty"`

	// id of identity platform
	Id int64 `json:"id,omitempty"`

	// secret key of identity platform
	Key string `json:"key,omitempty"`

	// name of identity platform
	Name string `json:"name,omitempty"`

	// num of successful authorization
	SuccessNum int64 `json:"success_num,omitempty"`

	// type of identity platform
	Type_ string `json:"type,omitempty"`

	// time of updating identity platform
	Update time.Time `json:"update,omitempty"`

	// url of identity platform
	Url string `json:"url,omitempty"`

	Uuid string `json:"uuid,omitempty"`
}
