/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type IdentityPlatformNestview struct {

	// id of identity platform
	Id int64 `json:"id,omitempty"`

	// name of identity platform
	Name string `json:"name,omitempty"`
}
