/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// License is used to manage backend license @grpc-models-proto
type License struct {

	Active bool `json:"active,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Customer string `json:"customer,omitempty"`

	ExpiredTime time.Time `json:"expired_time,omitempty"`

	Features []ProductFeature `json:"features,omitempty"`

	Id int64 `json:"id,omitempty"`

	Limits *ProductLimits `json:"limits,omitempty"`

	ProductInfo *ProductInfo `json:"product_info,omitempty"`

	Services []ProductService `json:"services,omitempty"`

	SignedTime time.Time `json:"signed_time,omitempty"`

	Status string `json:"status,omitempty"`

	UsedCapacity int64 `json:"used_capacity,omitempty"`

	UsedHostNum int64 `json:"used_host_num,omitempty"`

	Uuid string `json:"uuid,omitempty"`

	// v2, load from license info
	Version string `json:"version,omitempty"`
}
