/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ObjectStorageKey defines access key and secret key for object storage
type ObjectStorageKey struct {

	AccessKey string `json:"access_key,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Id int64 `json:"id,omitempty"`

	Reserved bool `json:"reserved,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`

	Status string `json:"status,omitempty"`

	Type_ string `json:"type,omitempty"`

	Update time.Time `json:"update,omitempty"`

	User *ObjectStorageUserNestview `json:"user,omitempty"`
}
