/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ObjectStoragePolicy is the model of object_storage_policy
type ObjectStoragePolicy struct {

	BucketNum int64 `json:"bucket_num,omitempty"`

	CachePool *PoolNestview `json:"cache_pool,omitempty"`

	Compress bool `json:"compress,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Crypto bool `json:"crypto,omitempty"`

	Default_ bool `json:"default,omitempty"`

	Description string `json:"description,omitempty"`

	Id int64 `json:"id,omitempty"`

	IndexPool *PoolNestview `json:"index_pool,omitempty"`

	Name string `json:"name,omitempty"`

	ObjectSizeThreshold int64 `json:"object_size_threshold,omitempty"`

	PolicyName string `json:"policy_name,omitempty"`

	Shared bool `json:"shared,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
