/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ObjectStorage is the model of object_storage
type ObjectStorage struct {

	ActionStatus string `json:"action_status,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Id int64 `json:"id,omitempty"`

	IndexPool *PoolNestview `json:"index_pool,omitempty"`

	LifecycleEndOn string `json:"lifecycle_end_on,omitempty"`

	LifecycleStartOn string `json:"lifecycle_start_on,omitempty"`

	MultiZoneEnabled bool `json:"multi_zone_enabled,omitempty"`

	Name string `json:"name,omitempty"`

	SearchEnabled bool `json:"search_enabled,omitempty"`

	SecondMergenceEnabled bool `json:"second_mergence_enabled,omitempty"`

	SecondMergenceEndOn string `json:"second_mergence_end_on,omitempty"`

	SecondMergenceStartOn string `json:"second_mergence_start_on,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
