/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

// ObjectStorageLifecycle is the model of object_storage_lifecycle
type ObjectStorageLifecycle struct {

	Id int64 `json:"id,omitempty"`

	Rules []interface{} `json:"rules,omitempty"`

	Status string `json:"status,omitempty"`
}
