/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ObjectStorageBucketStat define the object storage bucket statistics
type ObjectStorageBucketStat struct {

	DeleteObjCategory *OsBucketUsageCategory `json:"delete_obj_category,omitempty"`

	GetObjCategory *OsBucketUsageCategory `json:"get_obj_category,omitempty"`

	ListBucketCategory *OsBucketUsageCategory `json:"list_bucket_category,omitempty"`

	Objects int64 `json:"objects,omitempty"`

	PostObjCategory *OsBucketUsageCategory `json:"post_obj_category,omitempty"`

	PutObjCategory *OsBucketUsageCategory `json:"put_obj_category,omitempty"`

	UsedCapacityBytes map[string]int64 `json:"used_capacity_bytes,omitempty"`

	AllocatedObjects int64 `json:"allocated_objects,omitempty"`

	AllocatedSize int64 `json:"allocated_size,omitempty"`

	Create time.Time `json:"create,omitempty"`

	DelOpsPm float64 `json:"del_ops_pm,omitempty"`

	DownLatencyUs float64 `json:"down_latency_us,omitempty"`

	LatencyDown int64 `json:"latency_down,omitempty"`

	LatencyUp int64 `json:"latency_up,omitempty"`

	NumDown int64 `json:"num_down,omitempty"`

	NumUp int64 `json:"num_up,omitempty"`

	RxBandwidthKbyte float64 `json:"rx_bandwidth_kbyte,omitempty"`

	RxOpsPm float64 `json:"rx_ops_pm,omitempty"`

	TotalDelOps int64 `json:"total_del_ops,omitempty"`

	TotalDelSuccessOps int64 `json:"total_del_success_ops,omitempty"`

	TotalRxBytes int64 `json:"total_rx_bytes,omitempty"`

	TotalRxOps int64 `json:"total_rx_ops,omitempty"`

	TotalRxSuccessOps int64 `json:"total_rx_success_ops,omitempty"`

	TotalTxBytes int64 `json:"total_tx_bytes,omitempty"`

	TotalTxOps int64 `json:"total_tx_ops,omitempty"`

	TotalTxSuccessOps int64 `json:"total_tx_success_ops,omitempty"`

	TxBandwidthKbyte float64 `json:"tx_bandwidth_kbyte,omitempty"`

	TxOpsPm float64 `json:"tx_ops_pm,omitempty"`

	UpLatencyUs float64 `json:"up_latency_us,omitempty"`
}
