/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type ObjectStorageBucketNfsClientsResp struct {

	// nfs clients of object storage bucket
	OsBucketNfsClients []ObjectStorageBucketNfsClient `json:"os_bucket_nfs_clients"`
}
