/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// ObjectStorageGateway is the model of object_storage_gateway @grpc-models-proto
type ObjectStorageGateway struct {

	Create time.Time `json:"create,omitempty"`

	Description string `json:"description,omitempty"`

	GatewayIp string `json:"gateway_ip,omitempty"`

	GatewayName string `json:"gateway_name,omitempty"`

	Host *HostNestview `json:"host,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	OsZone *ObjectStorageZoneNestview `json:"os_zone,omitempty"`

	Port int64 `json:"port,omitempty"`

	Role string `json:"role,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
