/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// OSBucketLogging defines models of os bucket logging.
type OsBucketLogging struct {

	Create time.Time `json:"create,omitempty"`

	Id int64 `json:"id,omitempty"`

	Prefix string `json:"prefix,omitempty"`

	SourceBucketName string `json:"source_bucket_name,omitempty"`

	TargetBucketName string `json:"target_bucket_name,omitempty"`

	Update time.Time `json:"update,omitempty"`
}
