/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

// OSBucketUsageCategory contain usage info
type OsBucketUsageCategory struct {

	DownloadBytes int64 `json:"download_bytes,omitempty"`

	Ops int64 `json:"ops,omitempty"`

	UploadBytes int64 `json:"upload_bytes,omitempty"`
}
