/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// OSExternalStorageClass is the model of os external storage class +X:model:generate;plur=OSExternalStorageClasses;with_detailed
type OsExternalStorageClass struct {

	Create time.Time `json:"Create,omitempty"`

	Class int32 `json:"class"`

	Description string `json:"description,omitempty"`

	ExternalStoragePlatforms []OsExternalStoragePlatform `json:"external_storage_platforms"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	OsPolicyId int64 `json:"os_policy_id"`

	Platform string `json:"platform"`

	PlatformType string `json:"platform_type"`

	Status string `json:"status,omitempty"`

	StoragePattern []string `json:"storage_pattern,omitempty"`
}
