/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// OSExternalStoragePlatform is the model of os_external_storage_platform +X:model:generate;with_detailed;order_by=ID
type OsExternalStoragePlatform struct {

	AccessKey string `json:"access_key,omitempty"`

	Buckets []OsExternalStorageBucketInfo `json:"buckets,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Endpoint string `json:"endpoint,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`

	Status string `json:"status,omitempty"`

	Uuid string `json:"uuid,omitempty"`

	Weight int64 `json:"weight,omitempty"`
}
