/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

// OsdQos defines qos for osd
type OsdQos struct {

	Bandwidth int64 `json:"bandwidth,omitempty"`

	BandwidthMax int64 `json:"bandwidth_max,omitempty"`

	ClientThreshold int64 `json:"client_threshold,omitempty"`

	Id int64 `json:"id,omitempty"`

	Mode int64 `json:"mode,omitempty"`

	RecoveryRateType string `json:"recovery_rate_type,omitempty"`
}
