/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// Paging defines paging object
type Paging struct {

	Count int64 `json:"count,omitempty"`

	Duration int64 `json:"duration,omitempty"`

	DurationBegin time.Time `json:"duration_begin,omitempty"`

	DurationEnd time.Time `json:"duration_end,omitempty"`

	Limit int64 `json:"limit,omitempty"`

	Next string `json:"next,omitempty"`

	Offset int64 `json:"offset,omitempty"`

	Period string `json:"period,omitempty"`

	TotalCount int64 `json:"total_count,omitempty"`

	Truncated bool `json:"truncated,omitempty"`
}
