/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type PlacementNodeCreateReqPlacementNode struct {

	IsWitness bool `json:"is_witness,omitempty"`

	Name string `json:"name"`

	ParentId int64 `json:"parent_id"`

	Type_ string `json:"type"`
}
