/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// RoleMapping defines role mappings for auth
type RoleMapping struct {

	// time of creating identity platform
	Create time.Time `json:"create,omitempty"`

	// id of role mapping
	Id int64 `json:"id,omitempty"`

	// identity platform of role mapping
	IdentityPlatform *IdentityPlatformNestview `json:"identity_platform,omitempty"`

	// mapped role of sds platform
	Role string `json:"role,omitempty"`

	// time of updating identity platform
	Update time.Time `json:"update,omitempty"`

	// roles of external identity platform
	Value string `json:"value,omitempty"`
}
