/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// S3LoadBalancerGroup groups s3 load balancer with vips
type S3LoadBalancerGroup struct {

	ActionStatus string `json:"action_status,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Description string `json:"description,omitempty"`

	HttpsPort int64 `json:"https_port,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Port int64 `json:"port,omitempty"`

	Roles []string `json:"roles,omitempty"`

	SearchHttpsPort int64 `json:"search_https_port,omitempty"`

	SearchPort int64 `json:"search_port,omitempty"`

	SslCertificate *SslCertificateNestview `json:"ssl_certificate,omitempty"`

	Status string `json:"status,omitempty"`

	SyncPort int64 `json:"sync_port,omitempty"`

	Update time.Time `json:"update,omitempty"`

	WebConsoleEndpoint string `json:"web_console_endpoint,omitempty"`
}
