/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

// Snapshot is the corresponding rbd snapshot
type Snapshot struct {

	ActionStatus string `json:"action_status,omitempty"`

	AllocatedSize int64 `json:"allocated_size,omitempty"`

	BlockVolumeGroupSnapshot *VolumeGroupSnapshotNestview `json:"block_volume_group_snapshot,omitempty"`

	ClonedBlockVolumeNum int64 `json:"cloned_block_volume_num,omitempty"`

	Create time.Time `json:"create,omitempty"`

	Creator string `json:"creator,omitempty"`

	Description string `json:"description,omitempty"`

	Hidden bool `json:"hidden,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Passive bool `json:"passive,omitempty"`

	Pool *PoolNestview `json:"pool,omitempty"`

	Protected bool `json:"protected,omitempty"`

	// the snapshot is replicated from a remote cluster
	RemoteCluster *RemoteClusterNestview `json:"remote_cluster,omitempty"`

	Reserved bool `json:"reserved,omitempty"`

	Size int64 `json:"size,omitempty"`

	SnapName string `json:"snap_name,omitempty"`

	Status string `json:"status,omitempty"`

	Update time.Time `json:"update,omitempty"`

	Volume *VolumeNestview `json:"volume,omitempty"`
}
