/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

import (
	"time"
)

type TrashResourceNestview struct {

	Create time.Time `json:"create,omitempty"`

	ExpireTime time.Time `json:"expire_time,omitempty"`

	Id int64 `json:"id,omitempty"`

	ResourceId int64 `json:"resource_id,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`
}
