/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type UserUpdateReqUser struct {

	// email of user
	Email string `json:"email"`

	// enable or disable the user
	Enabled bool `json:"enabled"`

	// name of user
	Name string `json:"name"`

	// roles of user
	Roles []string `json:"roles,omitempty"`
}
