/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type VolumeMigrateReqVolume struct {

	// migrate destination pool
	DestPoolId int64 `json:"dest_pool_id"`

	MigrationStripes int64 `json:"migration_stripes,omitempty"`
}
