/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type VolumeFailedTask struct {

	Abort float64 `json:"abort,omitempty"`

	Busy float64 `json:"busy,omitempty"`

	CheckCond float64 `json:"check_cond,omitempty"`

	ResvConflict float64 `json:"resv_conflict,omitempty"`
}
