/*
 * XMS API
 *
 * XMS is the controller of distributed storage system
 *
 * API version: SDS_4.2.000.0.200302
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package xmsclient

type VolumeReplicationSetReqVolume struct {

	// destination pool id
	DestPoolId int64 `json:"dest_pool_id"`

	// destination volume name
	DestVolumeName string `json:"dest_volume_name"`

	// block replication policy id
	DpBlockReplicationPolicyId int64 `json:"dp_block_replication_policy_id"`
}
